#!/bin/bash

MD5SUM='cat /root/crontabsum'
NEWSUM='md5sum /etc/crontab | cut -d " " -f 1'

if [ "$MD5SUM" != "$NEWSUM" ]
then
	md5sum /etc/crontab | cut -d " " -f 1 > /root/crontabsum
	mail -s "The file crontab was modified" root@localhost.com < /etc/crontab
fi

echo '0 0 1 * * root sh /root/Desktop/init/04' | crontab

crontab -l
